### ISSUE TITLE
Application is not cleanly exiting

### ISSUE THREAD

**Issue by orestis** [ghtdak/qtreactor#1]
Hello,

I'm using qt4reactor in a PyQt4 windows application. I'm using Python 2.6 and PyQt 4.5.4

I'm installing the reactor as follows:

```
   import qt4reactor
   app = QApplication(sys.argv)
   qt4reactor.install()

   # instantiate windows here

  from twisted.internet import reactor
  reactor.runReturn()
  sys.exit(app.exec_())
```

The problem I'm seeing is when I'm exiting the app (by closing the window), control doesn't immediately return to the shell. I have to hit Ctrl-C, then I get the following error:

```
QObject::killTimers: timers cannot be stopped from another thread
```

Then control returns to the shell.

From what I can gather I'm doing everything right.

Additionally, I've tried the following:

```
    def quit():
        app.quit()
        from twisted.internet import reactor
        reactor.stop()
        sys.exit()
    QtCore.QObject.connect(app, QtCore.SIGNAL("lastWindowClosed()"), quit)
```

and in the qt4reactor.py:

```
    def stop(self):
        super(QTReactor, self).stop()
        self._timer.stop()
```

With this combination I could sometimes exit cleanly but it's not consistent.

**Comment by ghtdak** [comment]
The threads thing seems strange.  There shouldn't be other threads unless you're launching them... which I'm fairly sure you're not or you'd probably have hunted there.

A while back, Anita wrote:

Instead of calling reactor.run() to start twisted, I am now doing this:

"""
import qt4reactor
import sys

from PyQt4 import QtGui
app = QtGui.QApplication(sys.argv)
qt4reactor.install()

reactor.runReturn()
sys.exit(app.exec_())
"""

This seems to solve my issue.  I saw that a couple of others were having the same issue, so I thought I'd pass along my solution.

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

So, I'm not sure.  It appears that you're doing things right.

Perhaps genjix can offer guidance.  He's worked the PySide issue and may have some insights.

Sorry... I'll look more deeply if I get a chance.

-glenn

**Comment by orestis** [comment]
Thanks for the reply. I'll try to get a minimal reproduction ASAP.

**Comment by orestis** [comment]
Hi Glenn,

it seems that the issue is with IbPy that uses QThreads behind the scenes. This probably messes things up. From browsing past discussions on the google code project for ibpy it looks like you've done some work on ibpy-twisted before. Any chance of releasing this work publicly?

Thanks,
Orestis

**Comment by ghtdak** [comment]
That would explain it the threading.  Yes, I did "hack" threads out and put IbPy on top of twisted...  (And it was a hack :-)

I'll post briefly here but we should probably take this discussion off-line (kinda not related to twisted qt stuff)

It can be done.  I did it... but there are issues. Troy generates the IbPy code from Java which requires a re-hack whenever he / IB updates their code.  Thats not a biggie but it is an issue.

More importantly, I don't think IbPy is the way you wanna nail to IB.

I'll send you an email and we can discuss further if you like.

-glenn

**Comment by genjix** [comment]
BTW, a workaround I use is:

```
def process(self):
    app.processEvents()
    reactor.callLater(0, self.process)



if __name__ == '__main__':
    # ...
    reactor.callLater(0, mainwindow.process)
    reactor.run()
```

That's under PySide.

**Comment by jonathan-marcus** [comment]
I've found this same issue from a different angle: if you do t.i.threads.deferToThread(...), then it creates a threadpool which does not get cleaned up. I added the following lines to my shutdown script to get it to work:

```
if reactor.threadpool is not None:
    reactor.threadpool.stop()
```

When I do this, my application now exits properly. Ideally, I think this code should be rolled into the qtreactor itself.
